import { Job, Contact } from '../types';

export const mockJobs: Job[] = [
  {
    id: '1',
    company: 'TechCorp Inc.',
    position: 'Senior Frontend Developer',
    location: 'San Francisco, CA (Remote)',
    status: 'applied',
    url: 'https://techcorp.com/careers',
    description: 'Looking for an experienced frontend developer with React expertise to join our team.',
    salary: '$120,000 - $150,000',
    notes: 'Applied through company website. Referred by Jane Smith.',
    contactName: 'Michael Johnson',
    contactEmail: 'mjohnson@techcorp.com',
    contactPhone: '555-123-4567',
    dateApplied: '2023-07-15T10:30:00Z',
    dateModified: '2023-07-15T10:30:00Z',
    nextSteps: 'Follow up in one week if no response',
  },
  {
    id: '2',
    company: 'InnovateSoft',
    position: 'Full Stack Developer',
    location: 'New York, NY',
    status: 'interviewing',
    url: 'https://innovatesoft.io/jobs',
    description: 'Building web applications with React and Node.js',
    salary: '$110,000 - $130,000',
    notes: 'Had initial phone screening. Technical interview scheduled.',
    contactName: 'Sarah Wilson',
    contactEmail: 'sarah@innovatesoft.io',
    contactPhone: '555-987-6543',
    dateApplied: '2023-07-10T14:15:00Z',
    dateModified: '2023-07-18T09:00:00Z',
    nextSteps: 'Prepare for technical interview',
    nextInterviewDate: '2023-07-25T15:00:00Z',
  },
  {
    id: '3',
    company: 'Global Solutions',
    position: 'React Developer',
    location: 'Chicago, IL (Hybrid)',
    status: 'offer',
    url: 'https://globalsolutions.com/careers',
    description: 'Working on their customer-facing web application',
    salary: '$105,000 - $125,000',
    notes: 'Received verbal offer. Awaiting formal offer letter.',
    contactName: 'David Lee',
    contactEmail: 'dlee@globalsolutions.com',
    contactPhone: '555-789-0123',
    dateApplied: '2023-06-30T11:45:00Z',
    dateModified: '2023-07-20T16:30:00Z',
    nextSteps: 'Review offer and negotiate if needed',
  },
  {
    id: '4',
    company: 'DataViz Analytics',
    position: 'Frontend Engineer',
    location: 'Remote',
    status: 'rejected',
    url: 'https://dataviz.co/jobs',
    description: 'Building data visualization dashboards',
    salary: '$100,000 - $120,000',
    notes: 'Received rejection email. Position filled internally.',
    contactName: 'Anna Park',
    contactEmail: 'anna@dataviz.co',
    dateApplied: '2023-07-05T09:20:00Z',
    dateModified: '2023-07-12T13:10:00Z',
  },
  {
    id: '5',
    company: 'Startup Ventures',
    position: 'React Native Developer',
    location: 'Austin, TX',
    status: 'applied',
    url: 'https://startupventures.com/jobs',
    description: 'Building cross-platform mobile applications',
    salary: '$115,000 - $135,000',
    notes: 'Applied through LinkedIn Easy Apply',
    dateApplied: '2023-07-18T15:45:00Z',
    dateModified: '2023-07-18T15:45:00Z',
    nextSteps: 'Follow up in one week',
  },
  {
    id: '6',
    company: 'CloudTech Solutions',
    position: 'UI/UX Developer',
    location: 'Seattle, WA (Hybrid)',
    status: 'interviewing',
    url: 'https://cloudtech.com/careers',
    description: 'Designing and implementing user interfaces for cloud applications',
    salary: '$95,000 - $115,000',
    notes: 'Completed first interview. Moving to technical assessment.',
    contactName: 'Robert Chen',
    contactEmail: 'rchen@cloudtech.com',
    dateApplied: '2023-07-08T13:30:00Z',
    dateModified: '2023-07-19T11:20:00Z',
    nextSteps: 'Complete technical assessment by Friday',
    nextInterviewDate: '2023-07-28T14:00:00Z',
  }
];

export const mockContacts: Contact[] = [
  {
    id: '1',
    name: 'Michael Johnson',
    email: 'mjohnson@techcorp.com',
    phone: '555-123-4567',
    company: 'TechCorp Inc.',
    position: 'Technical Recruiter',
    notes: 'Initial point of contact for TechCorp application',
    dateAdded: '2023-07-15T10:30:00Z',
  },
  {
    id: '2',
    name: 'Sarah Wilson',
    email: 'sarah@innovatesoft.io',
    phone: '555-987-6543',
    company: 'InnovateSoft',
    position: 'Engineering Manager',
    notes: 'Conducted my phone screening, very friendly',
    dateAdded: '2023-07-10T14:15:00Z',
  },
  {
    id: '3',
    name: 'David Lee',
    email: 'dlee@globalsolutions.com',
    phone: '555-789-0123',
    company: 'Global Solutions',
    position: 'HR Director',
    notes: 'Sends quick responses, best to reach via email',
    dateAdded: '2023-06-30T11:45:00Z',
  },
  {
    id: '4',
    name: 'Anna Park',
    email: 'anna@dataviz.co',
    company: 'DataViz Analytics',
    position: 'Talent Acquisition',
    notes: 'Met at tech conference, offered to refer me',
    dateAdded: '2023-07-05T09:20:00Z',
  },
  {
    id: '5',
    name: 'Robert Chen',
    email: 'rchen@cloudtech.com',
    company: 'CloudTech Solutions',
    position: 'Senior Developer',
    notes: 'Interviewed with, ask about React performance optimizations',
    dateAdded: '2023-07-08T13:30:00Z',
  }
];